# Generated by Django 6.0.1 on 2026-01-14 19:56

import apps.photos.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название события')),
                ('event_type', models.CharField(choices=[('wedding', 'Свадьба'), ('sport', 'Спортивное мероприятие'), ('concert', 'Концерт'), ('corporate', 'Корпоратив'), ('party', 'Вечеринка'), ('graduation', 'Выпускной'), ('children', 'Детский праздник'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип события')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('location', models.CharField(blank=True, max_length=500, verbose_name='Место проведения')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('date', models.DateField(verbose_name='Дата события')),
                ('default_price', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена за фото по умолчанию')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичное событие')),
                ('photos_count', models.PositiveIntegerField(default=0, verbose_name='Количество фото')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.photographerprofile', verbose_name='Фотограф')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original', models.ImageField(upload_to=apps.photos.models.photo_upload_path, verbose_name='Оригинал')),
                ('watermarked', models.ImageField(blank=True, null=True, upload_to=apps.photos.models.watermarked_upload_path, verbose_name='С водяным знаком')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.photos.models.thumbnail_upload_path, verbose_name='Превью')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='Высота')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Размер файла')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата съёмки')),
                ('camera_model', models.CharField(blank=True, max_length=100, verbose_name='Камера')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена')),
                ('status', models.CharField(choices=[('processing', 'Обрабатывается'), ('active', 'Активно'), ('sold', 'Продано'), ('deleted', 'Удалено'), ('hidden', 'Скрыто')], default='processing', max_length=20, verbose_name='Статус')),
                ('faces_count', models.PositiveIntegerField(default=0, verbose_name='Количество лиц')),
                ('faces_processed', models.BooleanField(default=False, verbose_name='Лица обработаны')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='photos.event', verbose_name='Событие')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='accounts.photographerprofile', verbose_name='Фотограф')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Причина запроса')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('response', models.TextField(blank=True, verbose_name='Ответ фотографа')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_deletion_requests', to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to=settings.AUTH_USER_MODEL, verbose_name='Заявитель')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to='photos.photo', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Запрос на удаление',
                'verbose_name_plural': 'Запросы на удаление',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_location', models.JSONField(verbose_name='Координаты лица')),
                ('face_encoding', models.JSONField(verbose_name='Кодировка лица')),
                ('match_confidence', models.FloatField(default=0.0, verbose_name='Уверенность совпадения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_faces', to=settings.AUTH_USER_MODEL, verbose_name='Распознанный пользователь')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='photos.photo', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Лицо на фото',
                'verbose_name_plural': 'Лица на фото',
            },
        ),
    ]
